### ISSUE TITLE
Running Numbat on cells coming from multiple samples

### ISSUE THREAD

**Issue by aelhossiny** [kharchenkolab/numbat#111]
Hi, first of all thank you for such an incredible package! 

My question is, do I have to run Numbat on each sample separately, or can I run it on cells pooled from multiple samples. I am trying to see I can detect clones that are conserved from different patients and I am afraid that separate analysis of the samples would miss fitting them together in the same pseudobulk profile.

If that is not feasible, which type of the outputs would you recommend for clustering the clones from different samples, so I can detect the similarities between different samples?

Thank you again!

**Comment by teng-gao** [comment]
Hi @aelhossiny ,

Thanks for the issue. You can run numbat jointly on multiple samples if they are coming from the same individual. Samples from different individuals should always be run separately since their genotypes differ; merging them would not provide any benefit in detection power. 

If you would like to compare/cluster CNV calls from multiple individuals, you can always do so using the single-cell CNV calls in `joint_post`. For more details please see this vignette:

https://kharchenkolab.github.io/numbat/articles/results.html#single-cell-cnv-calls
