### ISSUE TITLE
difference between subtrees and clones?

### ISSUE THREAD

**Issue by aelhossiny** [kharchenkolab/numbat#115]
What is the difference between the clones and the subtrees? It seems that both are pseudobulk representation for the phylogeny analysis but I am not sure what is the difference between both.

Thanks

**Comment by teng-gao** [comment]
Hi @aelhossiny ,

The subtrees are clades in the phylogeny (with mutations placed on the branches), whereas clones are groups of cells that have the same set of mutations (could be monophyletic or [paraphylytic](https://en.wikipedia.org/wiki/Paraphyly)). In the example tree below, each star marks a mutation on the tree. There are 3 subtrees (clades) defined by each of the three mutations (blue, red, blue+green). Green by itself is not a subtree because it's not a clade. The mutations also define 3 clones, which are blue, red, and green.
<img width="991" alt="image" src="https://user-images.githubusercontent.com/13375875/234976386-e9dfa14b-8ffe-4be7-8908-36691d65d519.png">

**Comment by aelhossiny** [comment]
That's helpful! Thank you!
