### ISSUE TITLE
Phylogeny on merged samples

### ISSUE THREAD

**Issue by freddie090** [kharchenkolab/numbat#130]
Hi, 

I have multiple samples from an experiment that have ~6000 cells of 10X scRNA data each. If I were to try and run NUMBAT on the entire merged experiment the BAMs would be too big. 

Is it possible to run NUMBAT on the independent samples, but then merge the samples for the phylogeny part of the analysis? (for example, as was done in figure 5a of the NUMBAT paper).

Additionally, if I were to subset the BAMs given some high quality cells, merge the subsetted samples and then run NUMBAT on these merged BAMs/expression matrices, would this improve the robustness of the analysis? ie is there any advantage to the samples being processed simultaneously vs independently? 

Thanks

**Comment by teng-gao** [comment]
Hi @freddie090 ,

You can genotype the samples (from the same individual) using the multi-sample mode of `pileup_and_phase` (you can provide a list of BAMs), and provide the combined `count_mat` and `alelle_df` in a single numbat run. Numbat should be able to handle 6000 cells fine. 

The advantage is that you get consistent CNV and clone calls across samples and get an integrated phylogeny. Genotyping using multiple samples can also improve phasing accuracy.

Best,
Teng

**Comment by freddie090** [comment]
Hi Teng, 

Ah great, okay - my hunch was the inference would be more robust if it had access to information from all samples at once. I'll give it a go!

Thanks - 
Freddie

**Comment by freddie090** [comment]
Hi @teng-gao - sorry, just to clarify: 

After running pileup and phase where I provide a list of BAM files and corresponding sample names (as comma separated values as a single argument, e.g.: `-- samples samp_1,samp_2,samp_3 \ --bams samp_1.bam,samp_2.bam,samp_3.bam` the script produces an 'allele_counts.tsv' file for each sample. 

Has the multi sample mode worked? I wasn't sure whether I should expect a single combined allele counts table for all samples. If not, then do you suggest manually merging the expression matrix and allele counts for each sample before running Numbat?

Best
Freddie

**Comment by teng-gao** [comment]
Yes you should get a separate allele count df for each sample. You can then concatenate them (ditto for expression count matrix) before feeding to `run_numbat`.

**Comment by teng-gao** [comment]
> Okay - and sorry final Q @teng-gao - are the sample identities preserved somewhere for distinguishing in the phylogeny plots later?

You can plot the sample identities associated with cell barcodes on a sidebar using the `annot =` option in [`plot_phylo_heatmap`](https://kharchenkolab.github.io/numbat/reference/plot_phylo_heatmap.html):

**Comment by nbahlis** [comment]
May I ask for quick clarification. I did run phasing and pileup on 2 samples from the same patient. After I concatenate allele-df and count_mat (using rbind and cbind) and run numbat I get the following below, any thought what is causing it

<error/dplyr:::mutate_error>
Error in `mutate()`:
ℹ In argument: `cell = factor(cell, cell_order)`.
Caused by error in `levels<-`:
! factor level [1797] is duplicated
---
Backtrace:
     ▆
  1. ├─numbat::run_numbat(...)
  2. │ └─numbat::plot_exp_roll(...)
  3. │   └─... %>% ggplot()
  4. ├─ggplot2::ggplot(.)
  5. ├─dplyr::mutate(., cell_index = as.integer(cell))
  6. ├─dplyr::mutate(., cluster = factor(cluster, rev(unique(cluster))))
  7. ├─dplyr::arrange(., cell)
  8. ├─dplyr::mutate(., cluster = cutree(hc, k = k)[as.character(cell)])
  9. ├─dplyr::mutate(., cell = factor(cell, cell_order))
 10. ├─dplyr:::mutate.data.frame(., cell = factor(cell, cell_order))
 11. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
 12. │   ├─base::withCallingHandlers(...)
 13. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 14. │     └─mask$eval_all_mutate(quo)
 15. │       └─dplyr (local) eval()
 16. └─base::factor(cell, cell_order)

**Comment by teng-gao** [comment]
@nbahlis you prob have cells with the same barcode in both samples

**Comment by nbahlis** [comment]
thank you @teng-gao for your prompt reply.  Fixed the "same barcode" issue. I am getting another error now:

Error in if (hom_rate > 0.4) { : missing value where TRUE/FALSE needed.
thank you again for your help
