### ISSUE TITLE
reorder cell order in heatmap output

### ISSUE THREAD

**Issue by patelgrp** [kharchenkolab/numbat#192]
Hi! 

I'm sort of embarassed to ask this, but I've been stuck trying to reorder the phylogenetic heatmap. Is there a way to get plot_phylo_heatmap or cnv_heatmap to ignore the clone architecture/phylogeny and generate a custom heatmap by inputting a specific cell order (in my case, specific based off transcriptomics-defined clusters)? I can't help but imagine that I'm missing a simple argument somewhere. Any help would be appreciated!

Thanks!
-Anand

**Comment by teng-gao** [comment]
Hi! If your cells are ordered by a tree/dendrogram you can just provide the custom tree (argument gtree which is a tbl_graph object from tidygraph). Otherwise, you can just modify the ggplot code inside the function to plot a heatmap without the tree 

https://github.com/kharchenkolab/numbat/blob/d21a5b1f47f005713eed8b2616bfaff9b668a00c/R/vis.R#L575-L624

**Comment by patelgrp** [comment]
Well, holy cow! That worked like a dream. 

For anyone else who might be interested, all I had to do was created a modified version of the plot_phylo_heatmap function and change one line (#531) to basically hard-set cell.order into my preferred ordering instead of using the phylogeny. 

Thanks Teng!
