### ISSUE TITLE
Mouse genetic background - Both parental strains are reference C57

### ISSUE THREAD

**Issue by radiasso** [kharchenkolab/numbat#198]
Hello,

I started going through the [Mouse tutorial](https://kharchenkolab.github.io/numbat/articles/mouse.html), but I got stuck already at the first Step for the preparation of the VCF file. It explains what to do with an F1 hybrid mouse, but our lab mice are all purely C57BL, so the two parental strains for a mouse are exactly the same. 

Does this mean that I can't run the Numbat tool on my data? 
In case I misunderstood, how am I supposed to proceed with two identical parental strains?

Thank you in advance!

**Comment by teng-gao** [comment]
Unfortunately Numbat analysis doesn't work for inbred (pure) strains, since they lack het SNPs.

**Comment by xliu38** [comment]
> Unfortunately Numbat analysis doesn't work for inbred (pure) strains, since they lack het SNPs.

Hello @teng-gao, I am trying to follow up on this question. I have followed the whole process to find out the p_cnv_y (allele-level post probability) is all 1's because our mouse is pure strain. Will it still make sense to use p_cnv_x (expression-level) to infer a cell's malignancy? 

Thanks in advance!
