### ISSUE TITLE
error in if (hom_rate > 0.4) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by nbahlis** [kharchenkolab/numbat#210]
I am running numbat with 2 serial samples from the same patient. After running pileup and phasing on the 2 samples simultaneously, I ran numbat after concatenating the count_mat and df_allele files for the 2 samples.
Numbat however exits with the following error:

if (hom_rate > 0.4) { : missing value where TRUE/FALSE needed

any help with this error is deeply appreciated

thank you

**Comment by frstyang** [comment]
Hi, I'm facing the same issue. Were you able to resolve this problem, and if so, would you mind explaining a bit how? 

Based on the [location](https://github.com/kharchenkolab/numbat/blob/fcbfdf47adf18c0542ca224a0d90f06f86be72ea/R/diagnostics.R#L183-L184) in the code where `hom_rate` is computed, the error seems to be because there aren't enough pseudobulks which pass the filtering in `check_contam`.
