### ISSUE TITLE
Clones in pseudobulk vs. tumour phylogeny

### ISSUE THREAD

**Issue by WalterMuskovic** [kharchenkolab/numbat#28]
Hi Teng,

This is more of a question than an issue, sorry if I've missed something obvious about it in the docs. I'm trying to visually assess each clone's CNVs using 

```
nb$bulk_clones %>% 
  plot_bulks(
    min_LLR = 50, # filtering CNVs by evidence
    legend = TRUE
    )
```
which produces the following plot:

![bulk_clones](https://user-images.githubusercontent.com/38969859/161895643-d99439ff-06b1-4162-8fb7-4d5a4c7d8fd0.png)

But I've noticed the number of clones (9) doesn't match the clones I visualise with

```
nb$mut_graph %>% plot_mut_history()
```

![tree](https://user-images.githubusercontent.com/38969859/161895663-80e6d4f3-f450-4031-8627-711721c15d97.png)

which has 7. Do you have any info on why the clones in each plot are different? And is it possible to produce a plot like that above with `plot_bulks()` for the same 7 clones that are presented in the phylogeny? My goal is just to visually assess the CNVs for each clone to try and get a feel for whether I need to adjust any of the run parameters.

Thanks again for your help.

**Comment by teng-gao** [comment]
Hi Walter,

This is definitely a valid question. The mutation history does not agree with the clone pseudobulks because the clones are defined based on the lineage estimated from the previous iteration. For example, if you read in `mut_graph_1.rds` and plot that using `plot_mut_history()`, you should see 9 clones instead of 7. Does this make sense?

I'm trying to decide whether it would make sense to add a final per-clone CNV retest procedure (https://github.com/kharchenkolab/numbat/blob/devel/R/main.R#L215-L246) after the final iteration, but the retested CNV calls will be from the previous iteration. Alternatively, one can run more iterations until the phylogeny stabilizes, so that the clones will be exactly the same between the current iteration and the previous one. 

Thanks,
Teng

**Comment by WalterMuskovic** [comment]
Thanks Teng that makes a lot of sense! While following your suggestion and plotting `mut_graph_1.rds` I realised I'd overlooked the default value of the second argument in `Numbat$new(out_dir, i = 2)` and have been visualising the results of iterations 1 an 2 (9 and 7 clones defined respectively):

```
# Plot tumour phylogenies for each iteration
library(tidyverse)
lapply(str_glue('~/Downloads/mut_graph_{1:5}.rds'), readRDS) %>%
  lapply(plot_mut_history) %>%
  wrap_plots(ncol=3) + 
  plot_annotation(title = 'Clones defined for each iteration',
                  tag_levels = c('1'))
```
![iteration_clones](https://user-images.githubusercontent.com/38969859/162094757-8cc9f9f0-7e6f-49f9-abbd-2b726cf0fb64.png)

But for this sample the phylogeny seems to become more stable after a few additional iterations:
```
# Plot the relationship between clones across iterations with clustree
library(clustree)
lapply(1:5, function(i){
  read_tsv(str_glue("~/Downloads/clone_post_{i}.tsv")) %>%
  select(cell,clone_opt) %>%
  rename(!!str_glue('Iteration{i}') := clone_opt)
  }) %>%
  reduce(inner_join, by="cell") %>%
  clustree("Iteration") +
  ggtitle("Relationships between clones defined in each iteration")
```
![clustree_numbat_clones](https://user-images.githubusercontent.com/38969859/162095337-9f8733a6-bb49-4f46-ad81-0f380166f4bb.png)

Numbat is producing some useful insights into the clonal structure of our brain cancer samples, so thanks again for a great piece of software!

**Comment by teng-gao** [comment]
Thanks Walter, really cool plot by the way!
