### ISSUE TITLE
Error: C stack usage  7970628 is too close to the limit

### ISSUE THREAD

**Issue by aranham** [kharchenkolab/numbat#30]
Hi Teng, 

I'm re-running on a subset of cells for which I had run Numbat successfully previously. However, it exits with error: "C stack usage  7970628 is too close to the limit"
I'm attaching the log file. I have the ulimit as unlimited. 

I would appreciate your help. Thanks. 
[log (4).txt](https://github.com/kharchenkolab/numbat/files/8543881/log.4.txt)

**Comment by evanbiederstedt** [comment]
Hi @aranham 

Debugging this correctly won't be easy. 

This error tells us you're hitting the memory limits of your machine. The problem is....that could be not true. 

**First things first:**
In terms of how to address this, there are a number of things we'd need to check together.  It would be best to give the full logs, and then run `Cstack_info()`  and `traceback()` so we could figure out what's going on. 

https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Cstack_info
https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/traceback

It would be useful to share the data as well, along with `sessionInfo()` and details of your machine/OS. Runtime will be useful as well.

> I'm re-running on a subset of cells for which I had run Numbat successfully previously.

Given it ran correctly previously on a larger dataset, the easiest solution could in fact just be to restart R. 

**RE: more background**

You might want to read up on a "stack overflow": https://en.wikipedia.org/wiki/Stack_overflow

Usually R users get this error if a function was written in R suffering from "deep recursion". It's possible we could modify something in Numbat, but....given this ran successfully on a larger dataset for you, it's probably that's not true. Then again, there are recursive functions in this code---perhaps the inferred probabilities are such that this would recursive indefinitely, which is indeed a software bug.

The other factor here is that numbat is inherently memory-intensive. 

Some other links and SO posts should explain how complicated this could get:
https://www.roelpeters.be/c-stack-error-limit/
https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit
https://community.rstudio.com/t/tidiest-way-to-do-recursion-safely-in-r/1408

Best, Evan

**Comment by teng-gao** [comment]
Hi, 

Could you let me know if `tree_list_1.rds` was produced in the output folder?

Thanks,
Teng

**Comment by teng-gao** [comment]
This is actually an `ape::ladderize` bug @evanbiederstedt 

```
> tree_list = readRDS(glue('{out_dir}/tree_list_1.rds'))
> tree = tree_list[[length(tree_list)]]
> tree %>% ape::ladderize() 
Error: C stack usage  7973764 is too close to the limit
```

**Comment by aranham** [comment]
Thanks Evan and Teng for your reply. 
I'm closing this issue because the error generated had to do with me using the old allele dataframe that was created from running the pileup and phasing script on all cells instead of using a new one created only for the subset of cells. It seems to run fine with the new allele dataframe. Sorry for the confusion. 

Best,
Michelle

**Comment by whtns** [comment]
Hi! It seems like treeio developers made a change to as.phylo to fix this issue, however plot_phylo_heatmap takes a very long time to run if I swap ape::as.phylo for treeio:as.phylo 

https://github.com/YuLab-SMU/treeio/issues/78

**Comment by whtns** [comment]
Hi! It looks like treeio developers put in a fix for this in treeio::as.phylo, however plotting deep trees takes a very long time. would it be possible to exclude the phylogeny from a plot_phylo_heatmap plot but still show inferred clones?

**Comment by evanbiederstedt** [comment]
> would it be possible to exclude the phylogeny from a plot_phylo_heatmap plot but still show inferred clones?

It sounds like you're recommending functionality to turn off this feature. 

I think that's possible----we welcome pull requests. Please make a PR against the develop branch and ask for a review.

**Comment by teng-gao** [comment]
Update: there is now a fix in the devel branch, although you also need to install the newest version of scistreer (v1.1.0):
```
devtools::install_github('https://github.com/kharchenkolab/scistreer')
devtools::install_github('https://github.com/kharchenkolab/numbat/tree/devel')
```

**Comment by stela2502** [comment]
@teng-gao - would it be possible to write which kind of fix was included? Cause I still get the same error. And honestly - it is annoying!

**Comment by stela2502** [comment]
I stupid question - is that still needed to fix the error? I get the same error and had to read https://github.com/kharchenkolab/numbat/issues/79 in order to understand/get an impression of the cause of the error.

I split up my data into batches of 1000 cells in order to make your program work. But then I get the LLR errors and in addition sometimes the C stack error. So I assumed the - too view cells with mutations - problem would be my issue.

But increasing this now to 5000 cells leads to even more C stack errors. So I do not think the too view cells is the basis of my problem. Please tell me if I am missing some important part here.

**Comment by stela2502** [comment]
I understand that the error might not be yours to fix - but is there any way one could just not do this part of the analysis? We are interested to differentiate between cancer and normal cells. If I am not mistaken I have no real interest in a phylogenetic tree of the cancer modifications. You help and insight would be very much appreciated!

**Comment by stela2502** [comment]
By the way - for me the tree_list_1.rds file does not get created. Do you need me to open a new issue for this?
